name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'Issue is marked as stale since there has been no activity for two weeks. It will be automatically closed in 5 days.'
          days-before-stale: 14
          days-before-close: 5
          exempt-issue-labels: 'bug'
